---
- hosts: "{{ dynamic_hosts }}"
  become: true
  become_method: sudo
  gather_facts: True
  tasks:
  ##############################
  # install docker
  ##############################
  - name: install docker
    yum:
      name='docker'
      state=latest

  ##############################
  # set daemon json fact
  ##############################
  - name: set daemon json fact
    set_fact:
      daemon_config: '{ "debug": true, "experimental": true, "metrics-addr": "0.0.0.0:9999" }'

  ##############################
  # create daemon json
  ##############################
  - name: create daemon.json
    copy: 
      content: "{{ daemon_config }}" 
      dest: /etc/docker/daemon.json
  
  ##############################
  # start docker service
  ##############################
  - name: service docker
    service:
      name=docker
      state=started
      enabled=yes